/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fixtures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fixtures */
        get: operations["fixtures_api_fixtures_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policies/{policy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Policy */
        get: operations["policy_api_policies__policy_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/encounters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Encounters */
        get: operations["encounters_api_encounters_get"];
        put?: never;
        /** Create */
        post: operations["create_api_encounters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/encounters/{encounter_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Encounter */
        get: operations["encounter_api_encounters__encounter_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/encounters/{encounter_id}/extraction-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extract */
        post: operations["extract_api_encounters__encounter_id__extraction_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/encounters/{encounter_id}/facts/{fact_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review */
        post: operations["review_api_encounters__encounter_id__facts__fact_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/encounters/{encounter_id}/note-sections/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Note */
        post: operations["note_api_encounters__encounter_id__note_sections__key__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/encounters/{encounter_id}/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export */
        post: operations["export_api_encounters__encounter_id__exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/encounters/{encounter_id}/exports/{export_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Export */
        get: operations["get_export_api_encounters__encounter_id__exports__export_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/encounters/{encounter_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit */
        get: operations["audit_api_encounters__encounter_id__audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApprovedFact
         * @description Clinician-attested state. The only fact state rules, note and FHIR may read.
         */
        ApprovedFact: {
            /** Value */
            value: components["schemas"]["HfDiagnosisValue"] | components["schemas"]["LvefValue"] | components["schemas"]["NyhaClassValue"] | components["schemas"]["RestingHeartRateValue"] | components["schemas"]["BloodPressureValue"] | components["schemas"]["CardiacRhythmValue"] | components["schemas"]["MedicationValue"] | components["schemas"]["BetaBlockerDoseStatusValue"] | components["schemas"]["ConditionHistoryValue"] | components["schemas"]["SymptomValue"];
            assertion: components["schemas"]["Assertion"];
            /** Evidence */
            evidence?: components["schemas"]["EvidenceSpan"][];
            /** Edited */
            edited: boolean;
            /** Attestation Note */
            attestation_note?: string | null;
            /** Approved By */
            approved_by: string;
            /**
             * Approved At
             * Format: date-time
             */
            approved_at: string;
        };
        /**
         * Assertion
         * @enum {string}
         */
        Assertion: "affirmed" | "negated" | "uncertain" | "hypothetical";
        /** AuditEvent */
        AuditEvent: {
            /** Id */
            id: string;
            /** Encounter Id */
            encounter_id: string;
            /** Seq */
            seq: number;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /**
             * Actor Kind
             * @enum {string}
             */
            actor_kind: "clinician" | "system";
            /** Actor Display */
            actor_display: string;
            type: components["schemas"]["AuditEventType"];
            /** Fact Id */
            fact_id?: string | null;
            /** Summary */
            summary: string;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
        };
        /**
         * AuditEventType
         * @enum {string}
         */
        AuditEventType: "encounter.created" | "extraction.completed" | "extraction.failed" | "fact.approved" | "fact.edited" | "fact.rejected" | "fact.reopened" | "fact.added" | "note.section_edited" | "note.section_reverted" | "note.section_accepted" | "prior_auth.readiness_changed" | "export.generated" | "export.blocked";
        /** AuthorizationPolicy */
        AuthorizationPolicy: {
            /** Id */
            id: string;
            /** Version */
            version: string;
            /**
             * Simulated
             * @constant
             */
            simulated: true;
            /** Display Name */
            display_name: string;
            /** Payer Display */
            payer_display: string;
            /** Disclaimer */
            disclaimer: string;
            medication: components["schemas"]["Drug"];
            /** Indication Text */
            indication_text: string;
            /** Requirements */
            requirements: components["schemas"]["PolicyRequirement"][];
        };
        /** BetaBlockerDoseStatusValue */
        BetaBlockerDoseStatusValue: {
            /**
             * Status
             * @enum {string}
             */
            status: "at_max_tolerated_dose" | "below_max_tolerated_dose" | "contraindicated" | "not_tolerated";
        };
        /** BloodPressureValue */
        BloodPressureValue: {
            /** Systolic */
            systolic: number;
            /** Diastolic */
            diastolic: number;
        };
        /**
         * CandidateFact
         * @description Immutable extraction proposal. Written once at ingest; never mutated by review.
         */
        CandidateFact: {
            /** Value */
            value: components["schemas"]["HfDiagnosisValue"] | components["schemas"]["LvefValue"] | components["schemas"]["NyhaClassValue"] | components["schemas"]["RestingHeartRateValue"] | components["schemas"]["BloodPressureValue"] | components["schemas"]["CardiacRhythmValue"] | components["schemas"]["MedicationValue"] | components["schemas"]["BetaBlockerDoseStatusValue"] | components["schemas"]["ConditionHistoryValue"] | components["schemas"]["SymptomValue"];
            assertion: components["schemas"]["Assertion"];
            /** Evidence */
            evidence: components["schemas"]["EvidenceSpan"][];
            model_confidence: components["schemas"]["ModelConfidence"];
            /** Rationale */
            rationale?: string | null;
            /** Flags */
            flags?: components["schemas"]["ReviewFlag"][];
        };
        /** CardiacRhythmValue */
        CardiacRhythmValue: {
            /**
             * Rhythm
             * @enum {string}
             */
            rhythm: "sinus" | "atrial_fibrillation" | "atrial_flutter" | "paced" | "other";
            /**
             * Source
             * @enum {string}
             */
            source: "ecg" | "monitor" | "exam" | "unspecified";
        };
        /** ConditionHistoryValue */
        ConditionHistoryValue: {
            /**
             * Condition
             * @enum {string}
             */
            condition: "atrial_fibrillation" | "atrial_flutter" | "sick_sinus_syndrome" | "third_degree_av_block" | "permanent_pacemaker" | "gastroesophageal_reflux_disease";
            /** Timing Text */
            timing_text?: string | null;
        };
        /**
         * CreateEncounterRequest
         * @description Create one of the packaged synthetic demonstration encounters.
         */
        CreateEncounterRequest: {
            /** Fixture Id */
            fixture_id: string;
        };
        /** CreateExportRequest */
        CreateExportRequest: {
            /** Expected Revision */
            expected_revision: number;
        };
        /** CriterionSource */
        CriterionSource: {
            /** Title */
            title: string;
            /** Organization */
            organization: string;
            /** Url */
            url: string;
            /** Section */
            section: string;
            /** Version Or Date */
            version_or_date: string;
            source_type: components["schemas"]["CriterionSourceType"];
        };
        /**
         * CriterionSourceType
         * @enum {string}
         */
        CriterionSourceType: "fda_prescribing_information" | "professional_guideline" | "payer_policy" | "application_specification";
        /**
         * Drug
         * @enum {string}
         */
        Drug: "metoprolol_succinate" | "carvedilol" | "bisoprolol" | "sacubitril_valsartan" | "lisinopril" | "losartan" | "valsartan" | "spironolactone" | "eplerenone" | "dapagliflozin" | "empagliflozin" | "furosemide" | "torsemide" | "bumetanide" | "ivabradine" | "digoxin" | "other";
        /** EncounterContext */
        EncounterContext: {
            /**
             * Encounter Date
             * Format: date
             */
            encounter_date: string;
            /**
             * Specialty
             * @enum {string}
             */
            specialty: "cardiology" | "gastroenterology";
            /** Visit Type */
            visit_type: string;
            /** Clinician Display */
            clinician_display: string;
            /** Location Display */
            location_display: string;
            /** Fixture Id */
            fixture_id?: string | null;
        };
        /** EncounterHeader */
        EncounterHeader: {
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Revision */
            revision: number;
            /** Review Revision */
            review_revision: number;
            patient: components["schemas"]["SyntheticPatient"];
            context: components["schemas"]["EncounterContext"];
        };
        /** EncounterListItem */
        EncounterListItem: {
            /** Id */
            id: string;
            /** Patient Display */
            patient_display: string;
            /** Encounter Date */
            encounter_date: string;
            /** Visit Type */
            visit_type: string;
            stage: components["schemas"]["WorkflowStage"];
            /** Readiness */
            readiness: string | null;
            /** Authorization Applicable */
            authorization_applicable: boolean;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** EncounterView */
        EncounterView: {
            encounter: components["schemas"]["EncounterHeader"];
            stage: components["schemas"]["WorkflowStage"];
            transcript: components["schemas"]["Transcript"];
            extraction: components["schemas"]["ExtractionSummary"];
            /** Facts */
            facts: components["schemas"]["Fact"][];
            fact_counts: components["schemas"]["FactCounts"];
            /** Note Sections */
            note_sections: components["schemas"]["NoteSectionView"][];
            prior_auth: components["schemas"]["PriorAuthEvaluation"] | null;
            authorization_policy: components["schemas"]["AuthorizationPolicy"] | null;
            export: components["schemas"]["ExportStatusView"];
        };
        /**
         * EvaluatorName
         * @enum {string}
         */
        EvaluatorName: "requested_medication" | "context_specialty" | "hf_diagnosis" | "lvef_at_most" | "nyha_in" | "sinus_rhythm" | "heart_rate_at_least" | "beta_blocker_optimized" | "blood_pressure_at_least";
        /**
         * EvidenceSpan
         * @description A verbatim, server-verified slice of one transcript segment.
         *     Invariant (checked by grounding): segment.text[char_start:char_end] == quote.
         */
        EvidenceSpan: {
            /** Segment Id */
            segment_id: string;
            /** Char Start */
            char_start: number;
            /** Char End */
            char_end: number;
            /** Quote */
            quote: string;
            speaker: components["schemas"]["Speaker"];
        };
        /** ExportBlockReason */
        ExportBlockReason: {
            /**
             * Code
             * @enum {string}
             */
            code: "pending_facts" | "no_approved_facts";
            /** Message */
            message: string;
            /** Fact Ids */
            fact_ids?: string[];
        };
        /** ExportDetail */
        ExportDetail: {
            /** Id */
            id: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Generated By */
            generated_by: string;
            /** Review Revision */
            review_revision: number;
            /** Is Stale */
            is_stale: boolean;
            /** Bundle */
            bundle: {
                [key: string]: unknown;
            };
            /** Manifest */
            manifest: components["schemas"]["ExportManifestEntry"][];
            /** Excluded */
            excluded: components["schemas"]["ExportExclusion"][];
        };
        /** ExportExclusion */
        ExportExclusion: {
            /** Fact Id */
            fact_id: string;
            /** Reason */
            reason: string;
        };
        /** ExportManifestEntry */
        ExportManifestEntry: {
            /** Resource Type */
            resource_type: string;
            /** Resource Id */
            resource_id: string;
            /** Fact Ids */
            fact_ids: string[];
        };
        /** ExportStatusView */
        ExportStatusView: {
            /** Can Export */
            can_export: boolean;
            /** Blocked Reasons */
            blocked_reasons: components["schemas"]["ExportBlockReason"][];
            latest: components["schemas"]["ExportSummary"] | null;
        };
        /** ExportSummary */
        ExportSummary: {
            /** Id */
            id: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Generated By */
            generated_by: string;
            /** Review Revision */
            review_revision: number;
            /** Is Stale */
            is_stale: boolean;
            /** Resource Counts */
            resource_counts: {
                [key: string]: number;
            };
        };
        /** ExtractionIssue */
        ExtractionIssue: {
            kind: components["schemas"]["ExtractionIssueKind"];
            /** Item Index */
            item_index?: number | null;
            /** Fact Type */
            fact_type?: string | null;
            /** Message */
            message: string;
            /** Detail */
            detail?: {
                [key: string]: unknown;
            };
        };
        /**
         * ExtractionIssueKind
         * @enum {string}
         */
        ExtractionIssueKind: "provider_error" | "invalid_json" | "envelope_invalid" | "too_many_facts" | "item_invalid" | "disallowed_assertion" | "unknown_segment" | "quote_not_found" | "ungrounded_fact";
        /** ExtractionRun */
        ExtractionRun: {
            /** Id */
            id: string;
            /**
             * Provider
             * @constant
             */
            provider: "mock";
            /** Model */
            model?: string | null;
            /** Prompt Version */
            prompt_version: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Completed At
             * Format: date-time
             */
            completed_at: string;
            /** Attempts */
            attempts: number;
            status: components["schemas"]["ExtractionRunStatus"];
            /** Accepted Fact Ids */
            accepted_fact_ids?: string[];
            /** Issues */
            issues?: components["schemas"]["ExtractionIssue"][];
            /** Raw Output */
            raw_output?: string | null;
        };
        /**
         * ExtractionRunStatus
         * @enum {string}
         */
        ExtractionRunStatus: "succeeded" | "succeeded_with_issues" | "failed";
        /** ExtractionSummary */
        ExtractionSummary: {
            latest_run: components["schemas"]["ExtractionRun"] | null;
            /** Run Count */
            run_count: number;
            /** Can Run */
            can_run: boolean;
            /**
             * Provider
             * @constant
             */
            provider: "mock";
        };
        /** Fact */
        Fact: {
            /** Id */
            id: string;
            fact_type: components["schemas"]["FactType"];
            origin: components["schemas"]["FactOrigin"];
            /** Extraction Run Id */
            extraction_run_id?: string | null;
            candidate?: components["schemas"]["CandidateFact"] | null;
            review: components["schemas"]["ReviewState"];
            approved?: components["schemas"]["ApprovedFact"] | null;
        };
        /** FactCounts */
        FactCounts: {
            /** Total */
            total: number;
            /** Pending */
            pending: number;
            /** Pending Flagged */
            pending_flagged: number;
            /** Approved */
            approved: number;
            /** Approved Edited */
            approved_edited: number;
            /** Rejected */
            rejected: number;
        };
        /**
         * FactOrigin
         * @enum {string}
         */
        FactOrigin: "extraction" | "clinician";
        /**
         * FactReviewAction
         * @enum {string}
         */
        FactReviewAction: "approve" | "approve_with_edit" | "reject" | "reopen";
        /**
         * FactType
         * @enum {string}
         */
        FactType: "hf_diagnosis" | "lvef" | "nyha_class" | "resting_heart_rate" | "blood_pressure" | "cardiac_rhythm" | "medication" | "beta_blocker_dose_status" | "condition_history" | "symptom";
        /** FixtureListItem */
        FixtureListItem: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /**
             * Purpose
             * @enum {string}
             */
            purpose: "golden" | "adversarial" | "simulation";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HfDiagnosisValue */
        HfDiagnosisValue: {
            /**
             * Hf Type
             * @enum {string}
             */
            hf_type: "hfref" | "hfmref" | "hfpef" | "unspecified";
            /**
             * Chronicity
             * @enum {string}
             */
            chronicity: "chronic" | "acute" | "acute_on_chronic" | "unspecified";
        };
        /** LvefValue */
        LvefValue: {
            /**
             * Percent
             * @description Point value, or lower bound of a stated range
             */
            percent: number;
            /**
             * Percent Upper
             * @description Only when a range was stated
             */
            percent_upper?: number | null;
            /**
             * Measured On Text
             * @description Date exactly as spoken ('June 12th'). Resolved deterministically.
             */
            measured_on_text?: string | null;
            /**
             * Modality
             * @enum {string}
             */
            modality: "echocardiogram" | "cardiac_mri" | "nuclear" | "other" | "unspecified";
        };
        /** MedicationValue */
        MedicationValue: {
            drug: components["schemas"]["Drug"];
            /**
             * Raw Name
             * @description Name as spoken, e.g. 'Farxiga'
             */
            raw_name: string;
            /** Dose Value */
            dose_value?: number | null;
            /**
             * Dose Unit
             * @description Null unless the unit was stated
             */
            dose_unit?: ("mg" | "mcg") | null;
            /**
             * Dose Text
             * @description Dose as spoken, e.g. '49/51'
             */
            dose_text?: string | null;
            /**
             * Frequency
             * @enum {string}
             */
            frequency: "daily" | "bid" | "tid" | "qhs" | "prn" | "other" | "unspecified";
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "planned" | "discontinued" | "held";
            /** Adherence Note */
            adherence_note?: string | null;
        };
        /**
         * ModelConfidence
         * @description Self-reported by the model. Poorly calibrated: used ONLY to raise a review flag,
         *     never to auto-approve and never by the rule engine.
         * @enum {string}
         */
        ModelConfidence: "high" | "medium" | "low";
        /** NoteLine */
        NoteLine: {
            /** Text */
            text: string;
            /** Fact Ids */
            fact_ids: string[];
        };
        /**
         * NoteSectionAction
         * @enum {string}
         */
        NoteSectionAction: "edit" | "revert_to_generated" | "accept";
        /**
         * NoteSectionKey
         * @enum {string}
         */
        NoteSectionKey: "subjective" | "objective" | "medications" | "assessment_plan";
        /** NoteSectionRequest */
        NoteSectionRequest: {
            /** Expected Revision */
            expected_revision: number;
            action: components["schemas"]["NoteSectionAction"];
            /** Text */
            text?: string | null;
        };
        /** NoteSectionView */
        NoteSectionView: {
            key: components["schemas"]["NoteSectionKey"];
            /** Title */
            title: string;
            /** Generated Lines */
            generated_lines: components["schemas"]["NoteLine"][];
            /** Pending Fact Count */
            pending_fact_count: number;
            /** Is Overridden */
            is_overridden: boolean;
            /** Override Text */
            override_text: string | null;
            /** Override Stale */
            override_stale: boolean;
            /** Effective Text */
            effective_text: string;
            /** Accepted */
            accepted: boolean;
            /** Acceptance Stale */
            acceptance_stale: boolean;
        };
        /** NyhaClassValue */
        NyhaClassValue: {
            /**
             * Nyha
             * @enum {string}
             */
            nyha: "I" | "II" | "III" | "IV";
            /**
             * Nyha Upper
             * @description Only when a range like 'II to III' was stated
             */
            nyha_upper?: ("I" | "II" | "III" | "IV") | null;
        };
        /**
         * OverallReadiness
         * @enum {string}
         */
        OverallReadiness: "READY" | "NEEDS_REVIEW" | "INCOMPLETE" | "NOT_MET";
        /** PolicyRequirement */
        PolicyRequirement: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Policy Text */
            policy_text: string;
            evaluator: components["schemas"]["EvaluatorName"];
            /** Params */
            params?: {
                [key: string]: unknown;
            };
            /** Fact Types */
            fact_types: components["schemas"]["FactType"][];
            /** Operator */
            operator: string;
            /** Threshold */
            threshold?: unknown | null;
            /** Unit */
            unit?: string | null;
            provenance_classification: components["schemas"]["ProvenanceClassification"];
            /** Provenance Note */
            provenance_note: string;
            /** Criterion Sources */
            criterion_sources?: components["schemas"]["CriterionSource"][];
            /**
             * Last Verified At
             * Format: date
             */
            last_verified_at: string;
        };
        /** PolicyView */
        PolicyView: {
            policy: components["schemas"]["AuthorizationPolicy"];
        };
        /** PriorAuthEvaluation */
        PriorAuthEvaluation: {
            /** Policy Id */
            policy_id: string;
            /** Policy Version */
            policy_version: string;
            /** Review Revision */
            review_revision: number;
            overall: components["schemas"]["OverallReadiness"];
            /** Requirements */
            requirements: components["schemas"]["RequirementEvaluation"][];
        };
        /**
         * ProvenanceClassification
         * @enum {string}
         */
        ProvenanceClassification: "supported_by_authoritative_source" | "payer_specific" | "application_specific_demo_rule" | "unsupported_or_unclear";
        /** RequirementEvaluation */
        RequirementEvaluation: {
            /** Requirement Id */
            requirement_id: string;
            status: components["schemas"]["RequirementStatus"];
            /** Explanation */
            explanation: string;
            /** Used Fact Ids */
            used_fact_ids?: string[];
            /** Pending Fact Ids */
            pending_fact_ids?: string[];
            /** Missing Fact Types */
            missing_fact_types?: components["schemas"]["FactType"][];
            /** Context Fields Used */
            context_fields_used?: string[];
        };
        /**
         * RequirementStatus
         * @enum {string}
         */
        RequirementStatus: "SATISFIED" | "MISSING" | "NOT_MET" | "REQUIRES_REVIEW";
        /** RestingHeartRateValue */
        RestingHeartRateValue: {
            /** Bpm */
            bpm: number;
        };
        /** ReviewFactRequest */
        ReviewFactRequest: {
            /** Expected Revision */
            expected_revision: number;
            action: components["schemas"]["FactReviewAction"];
            /** Value */
            value?: {
                [key: string]: unknown;
            } | null;
            assertion?: components["schemas"]["Assertion"] | null;
            /** Reason */
            reason?: string | null;
        };
        /**
         * ReviewFlag
         * @description Computed deterministically at ingest (see ARCHITECTURE.md §5.4). Flags draw the
         *     clinician's attention; they never change a fact's value or status.
         * @enum {string}
         */
        ReviewFlag: "model_low_confidence" | "value_not_in_evidence" | "hedged_language" | "patient_reported_measurement" | "conflicting_candidates" | "uncertain_or_hypothetical" | "evidence_is_question";
        /** ReviewState */
        ReviewState: {
            status: components["schemas"]["ReviewStatus"];
            /** Decided By */
            decided_by?: string | null;
            /** Decided At */
            decided_at?: string | null;
            /** Rejection Reason */
            rejection_reason?: string | null;
        };
        /**
         * ReviewStatus
         * @enum {string}
         */
        ReviewStatus: "pending" | "approved" | "rejected";
        /** RunExtractionRequest */
        RunExtractionRequest: {
            /** Expected Revision */
            expected_revision: number;
        };
        /**
         * Speaker
         * @enum {string}
         */
        Speaker: "clinician" | "patient" | "staff" | "other";
        /** SymptomValue */
        SymptomValue: {
            /**
             * Symptom
             * @enum {string}
             */
            symptom: "dyspnea_on_exertion" | "orthopnea" | "paroxysmal_nocturnal_dyspnea" | "peripheral_edema" | "fatigue" | "dizziness" | "palpitations" | "chest_pain" | "heartburn" | "acid_regurgitation" | "dysphagia" | "melena" | "hematemesis" | "unintentional_weight_loss";
            /** Detail Text */
            detail_text?: string | null;
        };
        /**
         * SyntheticPatient
         * @description Demographics come from the fixture and are never inferred by extraction.
         */
        SyntheticPatient: {
            /** Synthetic Mrn */
            synthetic_mrn: string;
            /** Given Name */
            given_name: string;
            /** Family Name */
            family_name: string;
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            /**
             * Administrative Gender
             * @enum {string}
             */
            administrative_gender: "male" | "female" | "other" | "unknown";
            /**
             * Synthetic
             * @default true
             * @constant
             */
            synthetic: true;
        };
        /** Transcript */
        Transcript: {
            /** Segments */
            segments: components["schemas"]["TranscriptSegment"][];
        };
        /** TranscriptSegment */
        TranscriptSegment: {
            /** Id */
            id: string;
            /** Seq */
            seq: number;
            speaker: components["schemas"]["Speaker"];
            /** Speaker Label */
            speaker_label: string;
            /** Text */
            text: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WorkflowStage
         * @description Derived, never stored. Evaluated top to bottom; first match wins.
         * @enum {string}
         */
        WorkflowStage: "exported" | "review_complete" | "in_review" | "extraction_failed" | "transcript_ready";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    fixtures_api_fixtures_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FixtureListItem"][];
                };
            };
        };
    };
    policy_api_policies__policy_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    encounters_api_encounters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterListItem"][];
                };
            };
        };
    };
    create_api_encounters_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEncounterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    encounter_api_encounters__encounter_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encounter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_api_encounters__encounter_id__extraction_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encounter_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunExtractionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_api_encounters__encounter_id__facts__fact_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encounter_id: string;
                fact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewFactRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    note_api_encounters__encounter_id__note_sections__key__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encounter_id: string;
                key: components["schemas"]["NoteSectionKey"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteSectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_api_encounters__encounter_id__exports_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encounter_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_export_api_encounters__encounter_id__exports__export_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encounter_id: string;
                export_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_api_encounters__encounter_id__audit_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encounter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
